apiVersion: v1
kind: Service
metadata:
  name: zebra-statserve-service-dev
  labels:
    role: hedra
    name: statserve
spec:
  ports:
  - port: 9001
    name: statserve-in
  selector:
    role: hedra
    name: statserve