apiVersion: apps/v1
#apiVersion: batch/v1
kind: Deployment
metadata:
  name: zebra-statserve-dev
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    role: hedra
    name: statserve
spec:
  selector:
    matchLabels:
      role: hedra
      name: statserve
  template:
    metadata:
      labels:
        role: hedra
        name: statserve
    spec:
      imagePullSecrets:
      {{- if .Values.image.pullSecrets }}
      {{- range $sec := .Values.image.pullSecrets }}
        - name: {{ $sec | quote }}
      {{- end }}
      {{- else }}
        - name: {{ template "application.name" . }}-gitlab-reg-key
      {{- end }}
      containers:
      - image: registry.gitlab.com/thezebra/libraries/zebra-statserve:main
        imagePullPolicy: Always
        name: statserve
        envFrom:
          - configMapRef:
              name: statserve-cm
        env:
          - name: GRPC_DNS_RESOLVER
            value: native
        volumeMounts:
          - mountPath: /data
            name: statserve-files
        ports:
            - containerPort: 9001
              name: statserve-out
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: statserve-files
        configMap:
          name: hedra-files-cm
      - name: statserve-env
        configMap:
          name: statserve-cm
