# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statserve.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='statserve.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fstatserve.proto\x1a\x1cgoogle/protobuf/struct.proto\"{\n\x10StatStreamUpdate\x12)\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x13\n\x0bstream_name\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\x12\x0b\n\x03\x62in\x18\x05 \x01(\t\"F\n\x06Stream\x12\x13\n\x0bstream_name\x18\x01 \x01(\t\x12\'\n\x06\x66ields\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"4\n\x12StatStreamResponse\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x0fStatStreamQuery\x12\x13\n\x0bstream_name\x18\x01 \x01(\t\"T\n\x14StatStreamFieldQuery\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04stat\x18\x03 \x01(\t\x12\x13\n\x0bstream_name\x18\x04 \x01(\t\"V\n\x11StatStreamSummary\x12,\n\x0b\x66ield_stats\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x13\n\x0bstream_name\x18\x02 \x01(\t\"\xd5\x01\n\x16StatStreamFieldSummary\x12)\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12&\n\x05stats\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06\x63ounts\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12*\n\tquantiles\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x13\n\x0bstream_name\x18\x05 \x01(\t2\xfd\x02\n\x10StatStreamServer\x12+\n\tAddStream\x12\x07.Stream\x1a\x13.StatStreamResponse\"\x00\x12\x37\n\x0bUpdateStats\x12\x11.StatStreamUpdate\x1a\x13.StatStreamResponse\"\x00\x12\x44\n\x14UpdateStatsStreaming\x12\x11.StatStreamUpdate\x1a\x13.StatStreamResponse\"\x00(\x01\x30\x01\x12\x38\n\x0eGetStreamStats\x12\x10.StatStreamQuery\x1a\x12.StatStreamSummary\"\x00\x12\x41\n\rGetFieldStats\x12\x15.StatStreamFieldQuery\x1a\x17.StatStreamFieldSummary\"\x00\x12@\n\x0cGetFieldStat\x12\x15.StatStreamFieldQuery\x1a\x17.StatStreamFieldSummary\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_STATSTREAMUPDATE = _descriptor.Descriptor(
  name='StatStreamUpdate',
  full_name='StatStreamUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='StatStreamUpdate.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='StatStreamUpdate.stream_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='StatStreamUpdate.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='StatStreamUpdate.value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bin', full_name='StatStreamUpdate.bin', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=172,
)


_STREAM = _descriptor.Descriptor(
  name='Stream',
  full_name='Stream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='Stream.stream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fields', full_name='Stream.fields', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=244,
)


_STATSTREAMRESPONSE = _descriptor.Descriptor(
  name='StatStreamResponse',
  full_name='StatStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='StatStreamResponse.field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='StatStreamResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=298,
)


_STATSTREAMQUERY = _descriptor.Descriptor(
  name='StatStreamQuery',
  full_name='StatStreamQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='StatStreamQuery.stream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=338,
)


_STATSTREAMFIELDQUERY = _descriptor.Descriptor(
  name='StatStreamFieldQuery',
  full_name='StatStreamFieldQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='StatStreamFieldQuery.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='StatStreamFieldQuery.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stat', full_name='StatStreamFieldQuery.stat', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='StatStreamFieldQuery.stream_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=424,
)


_STATSTREAMSUMMARY = _descriptor.Descriptor(
  name='StatStreamSummary',
  full_name='StatStreamSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_stats', full_name='StatStreamSummary.field_stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='StatStreamSummary.stream_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=512,
)


_STATSTREAMFIELDSUMMARY = _descriptor.Descriptor(
  name='StatStreamFieldSummary',
  full_name='StatStreamFieldSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='StatStreamFieldSummary.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stats', full_name='StatStreamFieldSummary.stats', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counts', full_name='StatStreamFieldSummary.counts', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantiles', full_name='StatStreamFieldSummary.quantiles', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='StatStreamFieldSummary.stream_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=728,
)

_STATSTREAMUPDATE.fields_by_name['metadata'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_STREAM.fields_by_name['fields'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_STATSTREAMSUMMARY.fields_by_name['field_stats'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_STATSTREAMFIELDSUMMARY.fields_by_name['metadata'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_STATSTREAMFIELDSUMMARY.fields_by_name['stats'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_STATSTREAMFIELDSUMMARY.fields_by_name['counts'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_STATSTREAMFIELDSUMMARY.fields_by_name['quantiles'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['StatStreamUpdate'] = _STATSTREAMUPDATE
DESCRIPTOR.message_types_by_name['Stream'] = _STREAM
DESCRIPTOR.message_types_by_name['StatStreamResponse'] = _STATSTREAMRESPONSE
DESCRIPTOR.message_types_by_name['StatStreamQuery'] = _STATSTREAMQUERY
DESCRIPTOR.message_types_by_name['StatStreamFieldQuery'] = _STATSTREAMFIELDQUERY
DESCRIPTOR.message_types_by_name['StatStreamSummary'] = _STATSTREAMSUMMARY
DESCRIPTOR.message_types_by_name['StatStreamFieldSummary'] = _STATSTREAMFIELDSUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatStreamUpdate = _reflection.GeneratedProtocolMessageType('StatStreamUpdate', (_message.Message,), {
  'DESCRIPTOR' : _STATSTREAMUPDATE,
  '__module__' : 'statserve_pb2'
  # @@protoc_insertion_point(class_scope:StatStreamUpdate)
  })
_sym_db.RegisterMessage(StatStreamUpdate)

Stream = _reflection.GeneratedProtocolMessageType('Stream', (_message.Message,), {
  'DESCRIPTOR' : _STREAM,
  '__module__' : 'statserve_pb2'
  # @@protoc_insertion_point(class_scope:Stream)
  })
_sym_db.RegisterMessage(Stream)

StatStreamResponse = _reflection.GeneratedProtocolMessageType('StatStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATSTREAMRESPONSE,
  '__module__' : 'statserve_pb2'
  # @@protoc_insertion_point(class_scope:StatStreamResponse)
  })
_sym_db.RegisterMessage(StatStreamResponse)

StatStreamQuery = _reflection.GeneratedProtocolMessageType('StatStreamQuery', (_message.Message,), {
  'DESCRIPTOR' : _STATSTREAMQUERY,
  '__module__' : 'statserve_pb2'
  # @@protoc_insertion_point(class_scope:StatStreamQuery)
  })
_sym_db.RegisterMessage(StatStreamQuery)

StatStreamFieldQuery = _reflection.GeneratedProtocolMessageType('StatStreamFieldQuery', (_message.Message,), {
  'DESCRIPTOR' : _STATSTREAMFIELDQUERY,
  '__module__' : 'statserve_pb2'
  # @@protoc_insertion_point(class_scope:StatStreamFieldQuery)
  })
_sym_db.RegisterMessage(StatStreamFieldQuery)

StatStreamSummary = _reflection.GeneratedProtocolMessageType('StatStreamSummary', (_message.Message,), {
  'DESCRIPTOR' : _STATSTREAMSUMMARY,
  '__module__' : 'statserve_pb2'
  # @@protoc_insertion_point(class_scope:StatStreamSummary)
  })
_sym_db.RegisterMessage(StatStreamSummary)

StatStreamFieldSummary = _reflection.GeneratedProtocolMessageType('StatStreamFieldSummary', (_message.Message,), {
  'DESCRIPTOR' : _STATSTREAMFIELDSUMMARY,
  '__module__' : 'statserve_pb2'
  # @@protoc_insertion_point(class_scope:StatStreamFieldSummary)
  })
_sym_db.RegisterMessage(StatStreamFieldSummary)



_STATSTREAMSERVER = _descriptor.ServiceDescriptor(
  name='StatStreamServer',
  full_name='StatStreamServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=731,
  serialized_end=1112,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddStream',
    full_name='StatStreamServer.AddStream',
    index=0,
    containing_service=None,
    input_type=_STREAM,
    output_type=_STATSTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateStats',
    full_name='StatStreamServer.UpdateStats',
    index=1,
    containing_service=None,
    input_type=_STATSTREAMUPDATE,
    output_type=_STATSTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateStatsStreaming',
    full_name='StatStreamServer.UpdateStatsStreaming',
    index=2,
    containing_service=None,
    input_type=_STATSTREAMUPDATE,
    output_type=_STATSTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetStreamStats',
    full_name='StatStreamServer.GetStreamStats',
    index=3,
    containing_service=None,
    input_type=_STATSTREAMQUERY,
    output_type=_STATSTREAMSUMMARY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFieldStats',
    full_name='StatStreamServer.GetFieldStats',
    index=4,
    containing_service=None,
    input_type=_STATSTREAMFIELDQUERY,
    output_type=_STATSTREAMFIELDSUMMARY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFieldStat',
    full_name='StatStreamServer.GetFieldStat',
    index=5,
    containing_service=None,
    input_type=_STATSTREAMFIELDQUERY,
    output_type=_STATSTREAMFIELDSUMMARY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATSTREAMSERVER)

DESCRIPTOR.services_by_name['StatStreamServer'] = _STATSTREAMSERVER

# @@protoc_insertion_point(module_scope)
